/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-08-28 07:32:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.34.jar", Long.valueOf(1535099623239L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1535099623225L));
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-nozawa/test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/glanq/WEB-INF/lib/struts2-core-2.3.34.jar!/META-INF/struts-tags.tld", Long.valueOf(1504613532000L));
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-nozawa/test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/glanq/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ホーム画面</title>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/home.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--    スライドの設定 -->\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $('.slider').bxSlider({\r\n");
      out.write("  \t  auto:true,\r\n");
      out.write("  \t  mode:'fade',\r\n");
      out.write("  \t  speed:1000,\r\n");
      out.write("  \t  infinite:true,\r\n");
      out.write(" \t  pager:false,\r\n");
      out.write("  \t  controls:false,\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.concept').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("//          300pxスクロールでscrollinが始動\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 200){\r\n");
      out.write("                $(this).addClass('scrollin');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.intro_title').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 200){\r\n");
      out.write("                $(this).addClass('scrollin2');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.BBQ1').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 200){\r\n");
      out.write("                $(this).addClass('scrollin3');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.BBQ2').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 200){\r\n");
      out.write("                $(this).addClass('scrollin4');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.BBQ3').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 200){\r\n");
      out.write("                $(this).addClass('scrollin5');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//左サイド\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.left1').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 250){\r\n");
      out.write("                $(this).addClass('scrollanime1');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.left2').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime2');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.left3').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime3');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.left4').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime4');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.left5').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime5');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.left6').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime6');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 右サイド\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.right1').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 250){\r\n");
      out.write("                $(this).addClass('scrollanime1');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.right2').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime2');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.right3').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime3');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.right4').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime4');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.right5').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime5');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(window).scroll(function (){\r\n");
      out.write("        $('.right6').each(function(){\r\n");
      out.write("            var elemPos = $(this).offset().top;\r\n");
      out.write("            var scroll = $(window).scrollTop();\r\n");
      out.write("            var windowHeight = $(window).height();\r\n");
      out.write("            if (scroll > elemPos - windowHeight + 300){\r\n");
      out.write("                $(this).addClass('scrollanime6');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_s_005finclude_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("<!-- \tgifファイルの埋め込み -->\r\n");
      out.write("<div id=\"gif\">\r\n");
      out.write("<iframe src=\"https://publish.animatron.io/4ab47b5b5272616eb6ab368f?w=1066&h=600&a=1&r=1&c=0\" width=\"1066\" height=\"600\" frameborder=\"0\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"space1\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"left\">\r\n");
      out.write("<div class=\"left1\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"left2\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"left3\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"left4\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"left5\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"left6\"></div><div class=\"space4\"></div>\r\n");
      out.write("<div class=\"left1\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"left2\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"left3\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"left4\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"left5\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"left6\"></div><div class=\"space1\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"center\">\r\n");
      out.write("<!-- サイトコンセプト -->\r\n");
      out.write("<div class=\"concept\">\r\n");
      out.write("<h2>GLANQとは？</h2>\r\n");
      out.write("<br>\r\n");
      out.write("GLANQとはGlamorousとBBQを併せた造語であり、<br>\r\n");
      out.write("それらの意味通り普段とは一風変わった<br>\r\n");
      out.write("「華やかで魅惑的なBBQ体験を提供したい」<br>という思いが込められています。<br>\r\n");
      out.write("お好きなものをお好きな分だけお届けします。\r\n");
      out.write("<br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"space1\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- 提携BBQ場の紹介 -->\r\n");
      out.write("<div class=\"BBQ_spot_introduction\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"intro_title\">\r\n");
      out.write("<h2>提携BBQ場の紹介</h2>\r\n");
      out.write("<br>\r\n");
      out.write("GlanQでは3つのBBQ場と提携しており、<br>食材を各BBQ場に送り完全手ぶらでBBQが楽しめます。<br>\r\n");
      out.write("タイプの異なる3つの中から場所をお選びいただけます。<br>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"space1\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"BBQ1\">\r\n");
      out.write("<h3>BBQ場1</h3>\r\n");
      out.write("\r\n");
      out.write("<img src=\"./images/basyo1.jpg\" width=\"100%\" height=\"100%\" alt=\"\" class=\"BBQ1_img\" >\r\n");
      out.write("\r\n");
      out.write("<div class=\"BBQ1_text\">\r\n");
      out.write("<p>お子様連れの方にオススメ♪</p>\r\n");
      out.write("<p>BBQ施設の隣には大きな公園が</p>\r\n");
      out.write("<p>隣接しているので</p>\r\n");
      out.write("<p>緑に囲まれた場所で楽しいBBQの時間を</p>\r\n");
      out.write("<p>過ごすことができます。\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"space2\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"BBQ2\">\r\n");
      out.write("<h3>BBQ場2</h3>\r\n");
      out.write("<div class=\"BBQ2_text\">\r\n");
      out.write("<p>隣に川が流れているのが</p>\r\n");
      out.write("<p>このBBQ場の最大のポイント！</p>\r\n");
      out.write("<p>太陽に照らされる眩しい川を</p>\r\n");
      out.write("<p>眺めながら食べるお肉は絶品でしょう♪</p></div>\r\n");
      out.write("<img src=\"./images/basyo2.jpg\" width=\"100%\" height=\"100%\" alt=\"\" class=\"BBQ2_img\" >\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"space2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"BBQ3\">\r\n");
      out.write("<h3>BBQ場3</h3>\r\n");
      out.write("<img src=\"./images/basyo3.jpg\" width=\"100%\" height=\"100%\" alt=\"\" class=\"BBQ3_img\">\r\n");
      out.write("<div class=\"BBQ3_text\">\r\n");
      out.write("<p>駅からたったの徒歩5分！</p>\r\n");
      out.write("<p>アクセスの良さが一番のBBQ場です。</p>\r\n");
      out.write("<p>手ぶらで気軽に楽しむことができるので</p>\r\n");
      out.write("<p>デートのプランにオススメです♪</p></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"right\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"right1\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"right2\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"right3\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"right4\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"right5\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"right6\"></div><div class=\"space4\"></div>\r\n");
      out.write("<div class=\"right1\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"right2\"></div><div class=\"space2\"></div>\r\n");
      out.write("<div class=\"right3\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"right4\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"right5\"></div><div class=\"space3\"></div>\r\n");
      out.write("<div class=\"right6\"></div><div class=\"space1\"></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"piston\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_s_005finclude_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005finclude_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:include
    org.apache.struts2.views.jsp.IncludeTag _jspx_th_s_005finclude_005f0 = (org.apache.struts2.views.jsp.IncludeTag) _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.IncludeTag.class);
    _jspx_th_s_005finclude_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005finclude_005f0.setParent(null);
    // /home.jsp(268,0) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005finclude_005f0.setValue("header.jsp");
    int _jspx_eval_s_005finclude_005f0 = _jspx_th_s_005finclude_005f0.doStartTag();
    if (_jspx_th_s_005finclude_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005finclude_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005finclude_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005finclude_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:include
    org.apache.struts2.views.jsp.IncludeTag _jspx_th_s_005finclude_005f1 = (org.apache.struts2.views.jsp.IncludeTag) _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.IncludeTag.class);
    _jspx_th_s_005finclude_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005finclude_005f1.setParent(null);
    // /home.jsp(390,1) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005finclude_005f1.setValue("footer.jsp");
    int _jspx_eval_s_005finclude_005f1 = _jspx_th_s_005finclude_005f1.doStartTag();
    if (_jspx_th_s_005finclude_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005finclude_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005finclude_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005finclude_005f1);
    return false;
  }
}
